version: "3.8"

services:
  mongo_db:
    container_name: database_container
    image: mongo:4.4
    restart: always
    volumes:
      - mongo_db:/data/db
    networks:
      - app_network

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo_db
    networks:
      - app_network

  # Uncomment and configure nginx as needed
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_container
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/ssl/nginx
  #   depends_on:
  #     - app
  #   networks:
  #     - app_network
        
volumes:
  mongo_db: {}

networks:
  app_network:
    driver: bridge
